In [1]:
import numpy as np

In [7]:
batch_size = 5
context_size = 189
length = 50
vocab = 5032

In [2]:
a = np.ndarray([batch_size, 239])

In [4]:
print(a.shape)
print(a)

(5, 239)
[[ 6.93801531e-310  6.93801531e-310  4.64633373e-310 ...  1.97694488e-258
   1.23755835e+214  1.96086582e+243]
 [ 4.63456076e+228  3.40724745e-085  2.93494605e+222 ...  2.45184737e+198
   6.79248175e+199  5.03931346e+223]
 [-1.52160119e-277  3.53792771e+070  2.76846990e-029 ...  2.24036299e-309
   7.04185941e+053 -8.53891920e-210]
 [ 3.90611123e+295  1.21313566e-176  6.80194554e+053 ...  1.69141965e+140
   3.53792745e+070  2.72835796e+183]
 [ 1.31101360e+060  3.25479436e+195  1.91561319e-154 ... -5.57152021e-210
   3.65279638e+233 -1.33390161e+296]]


In [5]:
a = a[:,context_size:]

In [6]:
print(a.shape)
print(a)

(5, 50)
[[             nan  1.13914118e+069  6.75849038e-109  7.23312106e-321
   4.44659081e-323  6.93800854e-310  4.64633353e-310  2.02763010e+174
   1.69375610e+190  8.69972236e+183  1.13990216e-094  4.73535073e+223
   3.41495614e+025  9.77099376e-153  1.38083749e+267  9.47751238e+170
   9.47359503e-154  3.77280114e+233  3.41486025e+025  9.77099376e-153
   1.38083749e+267  4.72218500e+257  2.64986849e+180  7.86242865e+199
   2.41915991e+198  1.27616418e-152  4.82406562e+228  4.47593816e-091
   4.47593816e-091  4.47593816e-091  1.18600496e-259  1.33856864e-152
   9.19596581e+170  7.26613246e+223  5.45733613e+156  1.81667905e-152
   1.95135196e+227  9.13600520e+242  3.52054409e+257  3.40324489e-085
   5.28626955e-085  1.12477849e-153  5.26047692e+170  4.82337433e+228
   1.46921998e+195  9.19596581e+170  9.13611935e+242  1.97694488e-258
   1.23755835e+214  1.96086582e+243]
 [ 6.80260836e+053  3.46816826e+193  8.78462163e-110  2.77615009e-186
   7.99210114e-172  3.33701068e-162  8.747718

In [9]:
probs = np.ndarray([batch_size, length+1, vocab])
print(probs.shape)
print(probs)

(5, 51, 5032)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [10]:
probs = probs[:,1:,:]

In [11]:
print(probs.shape)
print(probs)

(5, 50, 5032)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
